apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: agentbox-a2a
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/invoker-iam-disabled: "false"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: agentbox-a2a@PROJECT_ID.iam.gserviceaccount.com
      containerConcurrency: 10
      timeoutSeconds: 3300
      containers:
        - image: gcr.io/PROJECT_ID/agentbox-a2a:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: AGENTBOX_GATEWAY_URL
              value: http://localhost:3000
            - name: GOOGLE_CLOUD_PROJECT
              value: PROJECT_ID
            - name: EXPECTED_AUDIENCE
              value: SERVICE_URL_PLACEHOLDER
            - name: EXPECTED_CALLER_SA
              value: GEMINI_CALLER_SA_PLACEHOLDER
